### ISSUE TITLE
Property 'PhysicalResourceId' does not exist on type 'CloudFormationCustomResourceEvent'

### ISSUE THREAD

**Issue by paul-uz** [bifravst/cloudformation-helpers#211]
When trying to return a response, I;d like to use the PhysicalID from the event, as it is part of a stack and will have a unique value for the name.

But for some reason i get the following TS error

> Property 'PhysicalResourceId' does not exist on type 'CloudFormationCustomResourceEvent'. Did you mean 'LogicalResourceId'?
  Property 'PhysicalResourceId' does not exist on type 'CloudFormationCustomResourceCreateEvent'

**Comment by coderbyheart** [comment]
This project uses types from `@types/aws-lambda`, so this is a bug there. 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d63e32a2324ee77c655ba5eb89ed938bf9bf9825/types/aws-lambda/trigger/cloudformation-custom-resource.d.ts#L19-L30
